### 📊 Pandas Aggregation Methods
We will cover all these methods
| Method | Text Version | Description |
|--------|--------------|-------------|
| `df.count()` | `'count'` | Count non-null values |
| `df.sum()` | `'sum'` | Sum of values |
| `df.min()` | `'min'` | Minimum value |
| `df.idxmin()` | `'idxmin'` | Index of minimum value |
| `df.max()` | `'max'` | Maximum value |
| `df.idxmax()` | `'idxmax'` | Index of maximum value |
| `df.mean()` | `'mean'` | Arithmetic mean/average |
| `df.median()` | `'median'` | Median value |
| `df.std()` | `'std'` | Standard deviation |
| `df.var()` | `'var'` | Variance |
| `df.quantile()` | `'quantile'` | Quantile/percentile |
| `df.describe()` | `'describe'` | Full statistical summary |

In [8]:
import pandas as pd
from datasets import load_dataset

# Load datasets
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

In [ ]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])  # convert from str to int mean date stamp
print(type(df['job_posted_date'][0]))

<class 'pandas.Timestamp'>

In [9]:
df.describe()   # describe() method only show Numeric columns

       salary_year_avg  salary_hour_avg
count     22003.000000     10662.000000
mean     123286.274072        47.016598
std       48312.449482        21.890738
min       15000.000000         8.000000
25%       90000.000000        27.500000
50%      115000.000000        45.980000
75%      150000.000000        61.159996
max      960000.000000       391.000000

In [11]:
df['salary_year_avg'].median()

np.float64(115000.0)

In [14]:
min_salary = df['salary_year_avg'].idxmin() # Find index of Minimum salary
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [ ]:
df.groupby('job_title_short')[['salary_year_avg', 'salary_hour_avg']].median() # or min() and max() as well

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                   85000.0        40.362499
Cloud Engineer                     90000.0        40.000000
Data Analyst                       90000.0        32.615002
Data Engineer                     125000.0        58.500000
Data Scientist                    127500.0        47.500000
Machine Learning Engineer         106415.0        47.535000
Senior Data Analyst               111175.0        47.500000
Senior Data Engineer              147500.0        61.500000
Senior Data Scientist             155500.0        47.620003
Software Engineer                  99150.0        47.560001

In [ ]:
df.groupby('job_title_short')['salary_year_avg'].agg(['min','max', 'median']) # finding as combined form

                               min       max    median
job_title_short
Business Analyst           16500.0  387460.0   85000.0
Cloud Engineer             42000.0  280000.0   90000.0
Data Analyst               25000.0  650000.0   90000.0
Data Engineer              15000.0  525000.0  125000.0
Data Scientist             27000.0  960000.0  127500.0
Machine Learning Engineer  30000.0  325000.0  106415.0
Senior Data Analyst        30000.0  425000.0  111175.0
Senior Data Engineer       35000.0  425000.0  147500.0
Senior Data Scientist      45000.0  890000.0  155500.0
Software Engineer          28000.0  375000.0   99150.0